<?php

/**
 * @author Addshore
 *
 * @since 1.27
 */
class SpecialPageExecutor
{

    /**
     * @param SpecialPage $page The special page to execute
     * @param string $subPage The subpage parameter to call the page with
     * @param WebRequest|null $request Web request that may contain URL parameters, etc
     * @param Language|string|null $language The language which should be used in the context
     * @param User|null $user The user which should be used in the context of this special page
     *
     * @throws Exception
     * @return array( string, WebResponse ) A two-elements array containing the HTML output
     * generated by the special page as well as the response object.
     */
    public function executeSpecialPage(
        SpecialPage $page,
        $subPage = '',
        WebRequest $request = null,
        $language = null,
        User $user = null
    ) {
$trace = debug_backtrace();
	  error_log(__FILE__);
	  var_dump(__FUNCTION__);
     error_log( print_r( $trace, true ));
	  die();
    }

    /**
     * @param WebRequest|null $request
     * @param Language|string|null $language
     * @param User|null $user
     *
     * @return DerivativeContext
     */
    private function newContext(
        WebRequest $request = null,
        $language = null,
        User $user = null
    ) {
$trace = debug_backtrace();
	  error_log(__FILE__);
	  var_dump(__FUNCTION__);
     error_log( print_r( $trace, true ));
	  die();
    }

    /**
     * If we are trying to edit and no token is set, supply one.
     *
     * @param DerivativeContext $context
     */
    private function setEditTokenFromUser(DerivativeContext $context)
    {
$trace = debug_backtrace();
	  error_log(__FILE__);
	  var_dump(__FUNCTION__);
     error_log( print_r( $trace, true ));
	  die();
    }

    /**
     * @param SpecialPage $page
     * @param string $subPage
     *
     * @throws Exception
     * @return string HTML
     */
    private function getHTMLFromSpecialPage(SpecialPage $page, $subPage)
    {
$trace = debug_backtrace();
	  error_log(__FILE__);
	  var_dump(__FUNCTION__);
     error_log( print_r( $trace, true ));
	  die();
    }
}
